version: '3.8'

services:
  # Kafka 브로커 서비스 정의 (단일 인스턴스)
  kafka-broker:
    image: apache/kafka:latest
    hostname: kafka-broker # 컨테이너 내부 호스트명 설정
    container_name: kafka-broker
    ports:
      - "9092:9092" # 외부 포트:컨테이너 내부 포트 (클라이언트 통신용)
      - "9093:9093" # 외부 포트:컨테이너 내부 포트 (컨트롤러 내부 통신용)
    environment:
      KAFKA_CLUSTER_ID: "6967c70b-33d8-460c-a34c-934b0177bffc"
      KAFKA_NODE_ID: 1
      KAFKA_PROCESS_ROLES: broker,controller
      
      # Listener 등록
      KAFKA_LISTENERS: PLAINTEXT://0.0.0.0:9092,CONTROLLER://0.0.0.0:9093

      # 외부 노출
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka-broker:9092

      # security protocol map 추가 *** 매우 중요 ***
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: CONTROLLER:PLAINTEXT,PLAINTEXT:PLAINTEXT
      
      # controller quorum
      KAFKA_CONTROLLER_QUORUM_VOTERS: 1@kafka-broker:9093
      KAFKA_CONTROLLER_LISTENER_NAMES: CONTROLLER
      
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_GROUP_INITIAL_REBALANCE_DELAY_MS: 0
      
    volumes:
      # 데이터 영속성을 위한 로컬 볼륨 마운트
      - ./kafka_data:/var/lib/kafka/data
    restart: unless-stopped

      # --- Kafka UI 서비스 (새로 추가) ---
  kafka-ui:
    image: provectuslabs/kafka-ui:latest
    container_name: kafka-ui
    ports:
      - "8090:8080" # 웹 UI 접속 포트 (http://localhost:8080)
    environment:
      # Kafka 브로커 접속 주소 지정 (컨테이너 내부 호스트명 'kafka-broker' 사용)
      KAFKA_CLUSTERS_0_NAME: local-kafka-cluster
      KAFKA_CLUSTERS_0_BOOTSTRAPSERVERS: kafka-broker:9092 #임시, 추후 변경 필요
      # Topic 생성을 활성화 (선택 사항)
      KAFKA_CLUSTERS_0_TOPIC_CREATION_ENABLED: "true"
    depends_on:
      - kafka-broker
    restart: unless-stopped

##  가끔씩 kafka_data 데이터 지워줘야 kafka-ui가 잘 뜬다. rm -rf ./kafka_data/*